### ISSUE TITLE
Space usage

### ISSUE THREAD

**Issue by cristaloleg** [arbovm/levenshtein#4]
That's not true.
```
// This implemention is optimized to use O(min(m,n)) space.
```
You aren't comparing sizes of s1 and s2.

Should be added something like this:
```
if len_s1 > len_s2 {
	s1, s2 = s2, s1
}
```

**Comment by EVODelavega** [comment]
Not quite true, the `column` slice has its first and last argument initialised to the lengths of str2 and str1 respectively. Swapping them round is not needed: if the first string is empty, the distance will equal length of str2, and vice-versa
